# Site settings
title: Delay-Tolerant Blogging
description: "Delay and disruption tolerant networks, theONE simulator and other topics"
url: "http://www.julianofischernaves.me"
author:
  name: "Juliano Fischer Naves"
  email: "julianofischer@gmail.com"
  url: "http://www.julianofischernaves.me"


# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title/
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Custom variables
version: "1.1.1"

# Options
custom_header: false
custom_nav_footer: false
reverse: false


#allowing comments
comments: true
adsense: true


authors:
    juliano:
        display_name: Juliano
        gravatar:
        email: julianofischer@gmail.com
        github: julianofischer

gems:
    - jemoji
    - jekyll-sitemap
    - jekyll-paginate

highlighter: rouge
